import { Gender, ProvenanceInfo } from './types.js';
import { PatientIdentifier } from './patient-identifier.js';

export interface CanonicalPatient {
  internalId: string; // Internal UUID generated by MPI, NOT the NID/Iqama
  
  // Names (Bilingual support)
  givenName: string;
  familyName: string;
  givenNameAr?: string;
  familyNameAr?: string;
  
  // Core demographics
  gender: Gender;
  birthDate: string; // ISO 8601: YYYY-MM-DD
  
  // Nationality & Demographics
  nationality?: string;
  nationalityCode?: string; // ISO 3166-1 alpha-3 (e.g. SAU)
  maritalStatus?: string;
  
  // Contact info
  phone?: string;
  email?: string;
  address?: {
    line?: string;
    lineAr?: string;
    city?: string;
    cityAr?: string;
    district?: string;
    districtAr?: string;
    postalCode?: string;
    country?: string;
  };
  
  // Saudi-specific demographic extensions
  religion?: string; // e.g. "Islam"
  occupation?: string;
  
  // Multi-facility identity linkages
  identifiers: PatientIdentifier[];
  
  // Lineage & Metadata
  provenance: ProvenanceInfo;
  createdAt: string;
  updatedAt: string;
}
